networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
  rabbitmq:
  mysql:
services:
  mongodb:
    image: rameshm1/mongodb:latest
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - source: mongodb
        target: /data/db
        type: volume
  catalogue:
    image: rameshm1/catalogue:latest
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
    volumes:
      - source: redis
        target: /data
        type: volume
  user:
    image: rameshm1/user:latest
    container_name: user
    networks:
      - roboshop
    depends_on: 
      - redis
      - mongodb
  cart:
    image: rameshm1/cart:latest
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis
  mysql:
    image: rameshm1/mysql
    container_name: mysql
    networks:
      - roboshop
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume
  shipping:
    image: rameshm1/shipping
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - source: rabbitmq
        target: /var/lib/rabbitmq
        type: volume
  payment:
    image: rameshm1/payment
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq

  web:
    image: rameshm1/web
    container_name: web
    networks:
      - roboshop
    ports:
      - '80:80'
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

